name: chantier_plus
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  mapbox_search: ^3.0.0
  cloud_firestore: ^5.5.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  google_maps_flutter: ^2.10.0
  image_picker: ^1.1.2
  flutter_dotenv: ^5.2.1
  flutter_typeahead: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - 'assets/images/'
